# Generated by Django 3.1.4 on 2021-01-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, upload_to='news/image/%Y/%m/%d'),
        ),
    ]
