# Generated by Django 3.1.4 on 2021-01-09 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_auto_20210109_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(null=True, through='news.CategorySubscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
