# Generated by Django 3.1.5 on 2021-03-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210215_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headline',
            field=models.CharField(help_text='Заголовок', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(help_text='category name', through='news.PostCategory', to='news.Category'),
        ),
    ]
