# Generated by Django 3.1.5 on 2021-03-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210308_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_ru',
        ),
    ]
