# Generated by Django 3.1.7 on 2021-04-10 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('headline', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('post_text', models.TextField(verbose_name='Текст')),
                ('post_rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('post_picture', models.ImageField(blank=True, upload_to='news/image/%Y/%m/%d')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
