# Generated by Django 3.1.7 on 2021-04-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210410_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_rating',
            new_name='rating',
        ),
    ]
