# Generated by Django 3.1.7 on 2021-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20210414_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
