# Generated by Django 3.1.7 on 2021-04-17 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0014_post_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accepted_responses',
            field=models.ManyToManyField(related_name='accepted_responses', to=settings.AUTH_USER_MODEL, verbose_name='принятые отклики'),
        ),
        migrations.AlterField(
            model_name='post',
            name='responses',
            field=models.ManyToManyField(related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='отклики в ожидании'),
        ),
    ]
