# Generated by Django 3.1.7 on 2021-04-17 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0016_auto_20210417_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
